version: 2.1

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}
    - run:
        name: install dependencies
        command: pip install --user setuptools wheel poetry tox
    - run:
        name: run tox
        command: tox
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "poetry.lock" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          - TOXENV=lint
  safety:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment: TOXENV=safety
  py39:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment: TOXENV=py39

  py310:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment: TOXENV=py310

  py311:
    <<: *common
    docker:
      - image: circleci/python:3.11
        environment: TOXENV=py311

workflows:
  version: 2
  test:
    jobs:
      - safety
      - py39
      - py310
      # Not available /doesn't work on Circle
      # - py311
      # - lint
